import { withErrorHandling } from '@/common/hocs';
import HomePage from '@/modules/Home/page';


function Home() {
  return (
      <HomePage />
  );
}

export default withErrorHandling(Home, []);


// export async function generateMetadata(): Promise<Metadata> {
//   const result = await store.dispatch(userApi.endpoints.getListUser.initiate());
//   await Promise.all(store.dispatch(userApi.util.getRunningQueriesThunk()));
//   return {
//     title: 'Nguyễn Đình Át',
//     description: 'Generated by create next app',
//     openGraph: {
//       title: 'Nguyễn Đình Át',
//       description: 'Generated by create next app',
//       type: 'website',
//       url: 'https://example.com',
//       images: [
//         {
//           url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nextjs-logo.svg/1280px-Nextjs-logo.svg.png',
//           width: 800,
//           height: 600,
//           alt: 'Og Image Alt',
//         },
//       ],
//     }
//   };
// }
