import { userApi } from '@/lib/services/modules';
import { store } from '@/lib/services/store';
import ExampleClientComponent from '@/modules/ExampleClientComponent/page';
import type { Metadata } from 'next';
import { withErrorHandling } from '@/common/hocs';
import type { IUser } from '@/common/types';
import AuthGuard from '@/common/guards/AuthGuard';

type Props = {
  data: {
    users: IUser[];
  };
};

function Home({ data }: Props) {
  return (
    <AuthGuard>
      <ExampleClientComponent />
    </AuthGuard>
  );
}

export default withErrorHandling(Home, []);


// export async function generateMetadata(): Promise<Metadata> {
//   const result = await store.dispatch(userApi.endpoints.getListUser.initiate());
//   await Promise.all(store.dispatch(userApi.util.getRunningQueriesThunk()));
//   return {
//     title: 'Nguyễn Đình Át',
//     description: 'Generated by create next app',
//     openGraph: {
//       title: 'Nguyễn Đình Át',
//       description: 'Generated by create next app',
//       type: 'website',
//       url: 'https://example.com',
//       images: [
//         {
//           url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nextjs-logo.svg/1280px-Nextjs-logo.svg.png',
//           width: 800,
//           height: 600,
//           alt: 'Og Image Alt',
//         },
//       ],
//     }
//   };
// }
